### PR TITLE
Maps status code validation error to contain real/expected status codes

### LINKED ISSUE #167: Status code validation error message is wrong
Upon investigation of the [failing Dredd CI](https://travis-ci.org/apiaryio/dredd/jobs/534710787) after using the newest version of Gavel, I have found out that the error message for non-matching status code is not per spec.

## Current behavior

```
Real and expected data does not match.
```

> This is the default output of the `TextDiff` validator that Gavel uses for status codes validation.

## Expected behavior

```
Status code is '${real}' instead of '${expected}'
```

This is an explicit message that has been mapped manually previously:

https://github.com/apiaryio/gavel.js/blob/c03a0f917f5bb9ba37ea63e2171e06361c08e349/lib/mixins/validatable-http-message.js#L412-L420

It seems that this mapping has been lost during the refactoring. It needs to be added back for Gavel to behave per spec.

### PR DESCRIPTION
**Pull request by artem-zakharchenko**
Adds explicit mapping of `statusCode` validation results to produce expected error messages that include real and expected status codes. Fixes failing tests in Dredd pipeline when using the newest release of Gavel.

## GitHub

- Closes #167

### CODE REVIEW

File: lib/next/units/validateStatusCode.js [hunk 1]
```diff
@@ -10,13 +10,23 @@ const APIARY_STATUS_CODE_TYPE = 'text/vnd.apiary.status-code';
...
   const rawData = validator.validate();
+  const results = validator.evaluateOutputToResults();
 
   return {
     validator: 'TextDiff',
     realType: APIARY_STATUS_CODE_TYPE,
     expectedType: APIARY_STATUS_CODE_TYPE,
     rawData,
-    results: validator.evaluateOutputToResults()
+    results: results.map((result) =>
```
Comment (artem-zakharchenko) [inline lib/next/units/validateStatusCode.js]: It's safe to map since the output of `evaluateOutputToResults` is `[]` when no errors occurred.

**Comment by artem-zakharchenko** [comment]
I've also updated the tests that didn't seem to assert this validation output previously.

**Comment by artem-zakharchenko** [comment]
Absolutely agree. Will be covered in #159. Thanks!
