### PR TITLE
Core app prepare

### LINKED ISSUE #236: Current gavel.js won't work in Webpack
The jju library causes an error:

```
ERROR in ./~/jju/lib/utils.js Module not found: Error: Can't resolve 'fs' in 'apiary/node_modules/jju/lib'
```

See [start of the relevant internal discussion](https://apiary.slack.com/archives/C051PDUKE/p1562758557034700) where @kuba-kubula also suggested a solution:

> but since the code in `json-parse-helfulerror` is like 10 lines, you can get rid of the whole `jju` require, but load just `jju/parse`
> so I'd suggest throwing away `jph` and writing tiny wrapper around `jju/lib/parse` :slightly_smiling_face: which will make it a much much smaller bundle, once used as a package

Before we fix this we should introduce a test infrastructure which catches this type of problems - e.g. replacing browserify with a webpack.

### PR DESCRIPTION
**Pull request by artem-zakharchenko**
Prepares `gavel` to be used in the Core app.

## Changes

- Removes `json-parse-helpfulerror` dependency
- Removes `mochify` and `sinon` dev dependencies
- Removes `test:browser` pipeline
- Adds `jju` save dependency
- Adds custom `parseJson` utility wrapper around `jju.parse()` to stop relying on `fs`
- Removes ES features not supported in the stable spec (i.e. spreading in object literals)
- ~~Adds test suite that ensures `gavel` can be bundled in the browser~~
  - The build is configured to throw when any of NodeJS built-in modules are present in it. Therefore, it's the verification of browser compatibility de facto, cancelling any need of a dedicated test pipeline.
- Adds building of the `gavel` library into ~~CJS~~UMD

## GitHub

- Closes #236

### CODE REVIEW

File: lib/units/validateBody.js [hunk 1]
```diff
@@ -1,10 +1,11 @@
-const jph = require('json-parse-helpfulerror');
+// const parseJson require('json-parse-helpfulerror');
```
Comment (honzajavorek) [inline lib/units/validateBody.js]: leftover

File: lib/utils/parseJson.js [hunk 2]
```diff
@@ -0,0 +1,11 @@
+const { parse } = require('jju/lib/parse');
```
Comment (artem-zakharchenko) [inline lib/utils/parseJson.js]: Only `utils.js` relies on `fs`. `parse` module should be working fine in isolation, getting rid of `fs` dependency, comparing when importing the module entirely:

```js
const jju = require('jju')
```

File: lib/utils/parseJson.js [hunk 3]
```diff
@@ -0,0 +1,11 @@
...
+
+const parseJson = (json, revivew) => {
```
Comment (honzajavorek) [inline lib/utils/parseJson.js]: I think this is a good idea in to have a wrapper not only because of the `fs` issue, but also because in the past it happened already that we were switching the JSON parser implementations.

**Comment by kuba-kubula** [comment]
bravo

**Comment by artem-zakharchenko** [comment]
CI for PR failed due to the flaky test (#139). Restart should resolve the build status.
